apiVersion: v1
kind: Service
metadata:
  name: mariadb-db
  namespace: experiments
spec:
  selector:
    app: mariadb-db
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: LoadBalancer
