apiVersion: v1
kind: Service
metadata:
  name: employees-portal-jvm
  namespace: experiments
spec:
  selector:
    app: employees-portal-jvm
  ports:
  - port: 8084
    targetPort: 8080
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-portal-jvm
  namespace: experiments
spec:
  selector:
    matchLabels:
      app: employees-portal-jvm
  template:
    metadata:
      labels:
        app: employees-portal-jvm
    spec:
      containers:
      - name: employees-portal-jvm
        image: employee-portal-jvm
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1Gi"
            cpu: "2000m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: ENABLE_VT
            value: "true"
          - name: DB_HOST
            value: mariadb-db.experiments.svc.cluster.local
          - name: DB_PW
            valueFrom:
              secretKeyRef:
                name: mariadb-db-secret
                key: root-password
        ports:
        - containerPort: 8080
